version: 2.1
orbs:
    aws-cli: circleci/aws-cli@2.0.10
    aws-ecs: circleci/aws-ecs@1.9.10
    aws-ecr: circleci/aws-ecr@6.8.2
    workflows:
      build-and-deploy:
        jobs:
          - aws-ecr/build-and-push-image:      
             -run:  docker build -t 922325212896.dkr.ecr.ap-northeast-1.amazonaws.com/rails:latest 
                    docker push 922325212896.dkr.ecr.ap-northeast-1.amazonaws.com/rails:latest

          - aws-ecs/deploy-service-update:
              requires:
                - aws-ecr/build-and-push-image
                  family: '${MY_APP_PREFIX}-service'
                  cluster-name: '${MY_APP_PREFIX}-cluster'
                  container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
    