version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-ecr: circleci/aws-ecr@6.8.2

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - push-image
      - aws-ecs/deploy-service-update:
          requires:
            - push-image
          family: demo
          cluster-name: demo-club
          container-image-name-updates: 'container=nginx,tag=latest|container=rails,tag=latest'
      - migrate:
          requires:
            - push-image

jobs:
  push-image:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - setup_remote_docker

      #app
      - aws-ecr/build-and-push-image:
          repo: rails
      #nginx
      - aws-ecr/build-and-push-image:
          path: containers/nginx   
          repo: web

  migrate:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-ecs/run-task:
          cluster: demo-club
          task-definition: demo
          launch-type: EC2
          overrides: "{ \\\"containerOverrides\\\": [ { \\\"name\\\" : \\\"rails\\\" , \\\"command\\\" : [ \\\"rails\\\" , \\\"db:migrate\\\" ] } ] }"