version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.0.0
    aws-ecs: circleci/aws-ecs@1.1.0
    aws-ecr: circleci/aws-ecr@6.8.2
    workflows:
      build-and-deploy:
        jobs:
          push-image:
            working_directory: ~/app
            docker:
              - image: circleci/ruby:2.5.1
            steps:
              - checkout
              - setup_remote_docker

              #app
              - aws-ecr/build-and-push-image:
                  repo: my-app/app
              #nginx
              - aws-ecr/build-and-push-image:
                  docker: ./docker/containers/nginx/Dockerfile
                  repo: nginx
  jobs:
    run-task:
      steps:
        - aws-ecs/run-task:
            cluster: demo-club
            task-definition: demo
            launch-type: EC2
            overrides:  {\\\"containerOverrides": [ { \\\"name" : \\\"rails" , \\\"command" : [ \\\"rails" , \\\"db:migrate" ] , } ] }
    run-task:
      jobs:
        - run-task
